import type { NextPage } from "next";
import Head from "next/head";
import "antd/dist/antd.css";
import { Layout } from "antd";
import { Header } from "@/components/Layout/Header";
import { Content } from "@/components/Layout/Content";
import { Footer } from "@/components/Layout/Footer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Header>Header</Header>
        <main>
          <Content>Content</Content>
        </main>
        <Footer>Footer</Footer>
      </Layout>
    </div>
  );
};

export default Home;
